// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrayCorpChallenge.DataAcess.Context;

namespace TrayCorpChallenge.DataAcess.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20210801183357_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("TrayCorpChallenge.Domain.Enitites.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Inventory")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("72e7443d-a9ef-4c24-9685-950fbab975e7"),
                            Inventory = true,
                            Name = "Aspirador de Pó",
                            Value = 100.00m
                        },
                        new
                        {
                            Id = new Guid("a04c11eb-6aa3-4d66-bf57-8e0888112be3"),
                            Inventory = true,
                            Name = "Casaco",
                            Value = 30.00m
                        },
                        new
                        {
                            Id = new Guid("320efb40-e77f-4bb3-b4dc-8af179dc343a"),
                            Inventory = true,
                            Name = "Abajur",
                            Value = 20.00m
                        },
                        new
                        {
                            Id = new Guid("f32f6047-02ee-44f7-94f9-c32e2191ff62"),
                            Inventory = true,
                            Name = "Comoda",
                            Value = 350.00m
                        },
                        new
                        {
                            Id = new Guid("eabfffc1-5bca-437a-b7e8-cd8ded132358"),
                            Inventory = true,
                            Name = "Espelho",
                            Value = 80.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
