// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrayCorpChallenge.DataAcess.Context;

namespace TrayCorpChallenge.DataAcess.Migrations
{
    [DbContext(typeof(ProductContext))]
    partial class ProductContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("TrayCorpChallenge.Domain.Enitites.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Inventory")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("89e27947-d1c4-4aab-bf03-b0adf8bfcb19"),
                            Inventory = true,
                            Name = "Aspirador de Pó",
                            Value = 100.00m
                        },
                        new
                        {
                            Id = new Guid("847716f1-c6c8-4d02-9b05-01b686a0b248"),
                            Inventory = true,
                            Name = "Casaco",
                            Value = 30.00m
                        },
                        new
                        {
                            Id = new Guid("1fde9e37-dc03-4966-a1cd-edceccfbe597"),
                            Inventory = true,
                            Name = "Abajur",
                            Value = 20.00m
                        },
                        new
                        {
                            Id = new Guid("6430b90c-8f05-49b7-8ee1-0cd10d6404e7"),
                            Inventory = true,
                            Name = "Comoda",
                            Value = 350.00m
                        },
                        new
                        {
                            Id = new Guid("54db09d6-2daa-4d53-b3f9-8c524cb08f46"),
                            Inventory = true,
                            Name = "Espelho",
                            Value = 80.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
